# Dolt 主題版本
version = "0.3.X"

# Section (所有文章) 页面配置
[section]
  # special amount of posts in each section page
  # section 页面每页显示文章数量
  paginate = 30
  # date format (month and day)
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # amount of RSS pages
  # RSS 文章数目
  rss = 10
  # recently updated posts settings
  # 最近更新文章设置
  [section.recentlyUpdated]
    enable = true
    rss = true
    days = 30
    maxCount = 10
    
[page]
  # 是否使用系列導航
  seriesNavigation = true
  # 是否启用字数统计
  enableWordCount = false
  # 是否启用阅读时间估计
  enableReadingTime = false
  
  [page.math]
    enable = true
    blockLeftDelimiter = "\\["
    blockRightDelimiter = "\\]"
    inlineLeftDelimiter = "\\("
    inlineRightDelimiter = "\\)"
    copyTex = true
    mhchem = true

  # 目錄配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true

  # 代碼配置
  [page.code]
    # 默认展开显示的代码行数
    maxShownLines = 10
